### ISSUE TITLE
Did this work?

### ISSUE THREAD

**Issue by targetarchitecture** [burt202/sbrick-test#1]
Just curious to know if this worked as I have just bought an sbrick.

Thanks

John in York

**Comment by burt202** [comment]
Hi John, it does work but its far from reliable as its using experimental Bluetooth APIs.
Its been a while since I last played around with this so maybe there have been improvements since.
I have created a readme regardless to help you have a play too. If you find/work anything out or can improve the code then please do share.

Cheers
